apiVersion: v1
kind: Service
metadata:
  # Назва Service, зазвичай береться з .Chart.Name та .Release.Name
  name: { { include "my-microservice-project.fullname" . } }
  labels: { { - include "my-microservice-project.labels" . | nindent 4 } }
spec:
  # Тип сервісу: ClusterIP (за замовчуванням), NodePort, LoadBalancer
  # ClusterIP: Доступний лише всередині кластера.
  # NodePort: Доступний на статичному порту на кожній ноді.
  # LoadBalancer: Створює хмарний балансувальник навантаження для зовнішнього доступу.
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: http # Посилається на порт з назвою 'http' у Deployment
      protocol: TCP
      name: http
  selector:
    { { - include "my-microservice-project.selectorLabels" . | nindent 4 } }
